### ISSUE TITLE
No results when entering command

### ISSUE THREAD

**Issue by ikrowni** [wjford/fight-bot#24]
Hey thanks for the bot. I'm having some problems with it though. I successfully added the bot but when i enter /fight or /fights i get no response from the bot.

Also is there anyway to trigger this to automatically embed the fights at certain times like 30m before an event start automatically embed the fights for the night.

**Comment by wjford** [comment]
@ikrowni Could you try adding the bot with the new link?

**Comment by ikrowni** [comment]
Seems to be working again. Thanks for fixing it and for looking into the automatic messaging.

**Comment by wjford** [comment]
Unfortunately the automatic posting does not seem possible with the new /slash commands that Discord's bot APIs are transitioning to.
